# 개발: 디버깅 최대, 스키마 자동 생성
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 콘솔
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 로깅
logging.level.com.example.study_board=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
